---
title: "Conclusion - What Now?"
author: "Asher Spector"
date: "May 5, 2018"
output: 
  html_document:
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: true
      smooth_scroll: false
---

This guide has gone through a solid amount of material. We've covered:

1. The motivation behind using RStudio and how to set up and use it
2. The purpose of Git/GitHub and how to use their basic functionality, covering everything from branching to merge conflicts
3. The proper way to structure and develop packages using RStudio and devtools (and roxygen2)
4. The proper way to test packages using testthat (and devtools)

#### Advanced tools for R

As you build larger and more complex packages, you might need a deeper understanding of package structure and development in R than the one provided in this package. For a slightly more in-depth explanation of package development, you'll want to reference Hadley Wickham's [R Packages](http://r-pkgs.had.co.nz/). For a serious dive into package mechanics, you might want to consult the official [R Extensions Manual](https://cran.r-project.org/doc/manuals/R-exts.html#Creating-R-packages), which is published by CRAN. However, at least for mid-sized packages, this guide probably has given you most of what you need to know.

#### Python and Other Languages

Of course, you might also want to develop packages in other programming languages besides R. You'll be happy to learn that quite a lot of the components of package development are very similar in other languages! For example, the setup.py file in Python packages  serves many of the same purposes as the DESCRIPTION file in R. Moreover, Git and GitHub support every programming language, and Travis/Appveyor support almost every major programming language (in fact, Travis/Appveyor support most languages *better* than they support R, although their R support is great too). However, devtools, roxygen2, testthat, and RStudio are unfortunately R-specific tools, which is too bad, because they're extremely useful. Thankfully, there are equivilent packages for most other major programming languages. Although we unfortunately can't compile a list of every package-building tool for every major language, we have written a list of helpful tools for Python (because it and R are the most popular languages for data science). Specifically,

  1. [This link from the PyPA (Python Packaging Authority)](https://packaging.python.org/tutorials/distributing-packages/#setup-py) provides an overview to package structure in Python.
  2. [This link from the setuptools documentation](https://setuptools.readthedocs.io/en/latest/setuptools.html) explains some of the best practices for building packages in python using the *setuptools* package. It's a bit like devtools (but not exactly the same). 
  3. Like roxygen2, [Sphinx](http://www.sphinx-doc.org/en/master/) can automatically generate documentation by parsing Python source code.
  4. Like testthat (although a bit more technical), the default Python package *unittest* can help you write unit tests in Python more easily. 
  5. [Pycharm](https://www.jetbrains.com/pycharm/) is a development environment which integrates a lot of the useful tools mentioned above and provides a framework for creating packages easily. There are also tons of wonderful IDE's for python, many of which are listed [here](https://wiki.python.org/moin/IntegratedDevelopmentEnvironments).
    
That's it for this guide! We hope you learned something useful. Again, if you have any comments on material, you should email amspector100@gmail.com with them. 

