---
title: "Using Github"
author: "Asher Spector"
date: "February 10, 2018"
output: html_document
---

Dev note: I recognize this is inefficiently written. When I finish writing out all the content, I will ruthlessly cut it down, don't worry :) 

This guide is a basic introduction to Git and Github for near-absolute beginners. It will start by discussing the importance of git and github, how to install git, and how to use git/github at a basic level. Lastly, it will provide links to further reading regarding advanced functionality for git.

## 1. Why use git/github

Git and github are actually two different things, and deserve their own sections. Before diving into specifics, however, it's important to recognize that git and github are just tools that developers use to more effectively organize their code. Git and github are designed to solve three main organizational problems.  

First, imagine that two programmers (we'll refer to them as Carlos and Grace) are working together to try to build a website that automatically displays polling results from US elections, and suppose Grace  modifies a script to slightly change the method for aggregating polling data. It would be tedious for Carlos and Grace to email the script back and forth each time they updated it. Instead, they need a repository where they can easily update  and sync their code to make sure they're on the same page. Github allows programmers to create such repositories. 

Second, imagine that farther along in the project, Grace decides that she needs to totally rewrite the code which stores and organizes polling data. Unfortunately, while Grace modifies the system which stores the data, it will be offline, which is unfortunate because Carlos needs to use the data for his work on the project. To avoid this dilemma, Git and Github allow programmers to create different versions, called branches, of their code. Using branching, Grace can modify the storage system, and in the meantime, Carlos can continue to use the old storage system for his work. 

Third, suppose that once Grace and Carlos have finished their website, they want to publish all the statistical functions and tools they built so that other researchers can use those tools to reproduce Grace and Carlos's research. It's often tedious to write documentation about huge quantities of code, but thankfully, Git and Github offer tools that allow programmers to more easily document their code. 

### What is git?

Git is a local version control system. In other words, Git automatically organizes and saves versions of code on your computer, but does not connect to the internet: it's purely accessible through the command prompt on a computer (there are also other ways to use git, but it's generally best to use the command prompt). Git organizes code in two ways.

First, Git sends discrete versions of code to a local database or repository on the computer on which it is installed. To understand this, imagine that Carlos is writing an R script which determines the proper weights for aggregating polling data, and at some point he finishes the first version of the script. At this point, Carlos can send his code to the local repository, in an action called *commiting* his script. We'll discuss how to do this later, but note that scripts are not automatically committed to the repository. If Carlos deleted all the code in the script and saved it, he could still access the script by going into the repository. Moreover, the repository also stores all of the previous versions of code, and can backtrack through the various commits, so if Carlos decides the version of the script he built last year worked better, he can use git to access it. 

Second, Git can create branches, or separate versions of code, on the computer it's installed to. Remember how Grace wanted to revamp the storage system for polling data without preventing Carlos from accessing the old storage system? Using Git, Grace should create a new *branch* in the repository. Creating a branch creates (for all practical purposes) an entirely separate version of the entire polling project in the Git repository, which Grace can modify and experiment with without compromising the functionality of the *master branch,* the original scripts that Grace had written. While she's working, Grace can use Git to move back and forth between the branches: doing so will make the contents of her R scripts (which show up in the same folder on her computer) seem to magically change. 

__ insert graphic demonstrating this property of branching __

Then, when Grace finishes designing and testing the new storage system, she can *merge* the two branches together, and Carlos's scripts will automatically start using the new storage system. 

(Insert graphic about organization of git, including branches, )

### What is github?

Where Git creates *local* repositories on an individual computer, Github allows programmers to create *remote* repositories, stored online, for their code. This is pretty simple concept, but it's extroardinarily useful. It means that when Grace finishes updating a series of scripts, she can simply *push* (push means send) them to Github, and then Carlos can in one command *pull* (download) the modified versions onto his computer to work with them. Github provides other important tools, but we will not discuss those until later. 

__ insert graphic about github, git, etc__

## 2. Setting up Git/Github

__ general problem - what about other OSs? __

### Making a Github account

Signing up for a Github is fairly simple - just go to github.com, click "sign up" in the upper right hand corner, and follow the instructions. We recommend, at least to begin with, getting a free version of Github.
(Note: ask Simo - we recommend this right?)

### How to Install and Set Up Git

Because Git is a form of *local* source control, it does require installation. To install Git onto your computer, go to one of the following sites:

  * For Linux: Head to https://git-scm.com/download/linux and follow the instructions.
  
  * For Windows: Go to https://git-scm.com/download/win and the download should automatically start.
  
  * For Mac: Click on https://git-scm.com/download/mac and the download should automatically start. 

If you are running Windows/Mac and the websites above download an installer, simply follow the instructions from the installer - it's fine to just use default settings for now. 

Before you can start using git, you do have to do a one time set up. Git is built to track and organize different versions of code, so it will need you to set your username and email before it will let you start modifying programs. To set your username and email after installing, open the command line on your computer and type the following commands into it:

```{R, eval=FALSE}
$ git config --global user.name "Your Name"
$ git config --global user.email "youremail@email.com"
```

__ insert screenshot of git bash/cmd line __

Now you're ready to start using Git/Github!

## 3. Starting to use Git/Github

### Creating Projects and Repositories

The first step to using git is creating a project, or repository (repo for short). There are generally two ways to create a repo in Git. 

#####Method 1: Start your project on Github

The first way to start a repo is by creating it on github. To do so, log into your Github account, click "Repositories" in the top tab, and then click the green "New" button on the right. 

__ do we want to insert pictures? __

Github will prompt you to choose a repository name and description of the repo, which you should enter, and will also ask you whether you'd like to initialize the repository with a README. You should generally add README and .gitignore files, although we'll discuss their functions and importance later. For now, just add the README. 

__ discussion of gitignores?? __

Once you've created the repository on Github, the next step is to link it with a local repository on git. To do this, open the *command prompt* on your computer. You'll need to enter a couple of commands to get the repo set up on your computer. 

First, you'll need to set the *working directory* in the command prompt. The working directory is the location where git and command prompt will do all of their editing - if you add a file, it will add the file into your working directory. Thus, before you download your repository, you'll want to navigate to the folder in which you want the repository to be located. For example, Carlos might want to put a repo in his "R" folder inside the "Documents" folder on my computer. To do this, you can use the 'cd' command, which stands for "change directory," and then copy and paste the path of the folder you'd like to place the repository in. An example is given below:

```{R, eval=FALSE}
$ cd C:/Users/Carlos/Documents/R
```

Next, you will need to tell git to download, or *clone*, the repo. You can do this using the "git clone" command, which allows you to download and sync a repository *for the first time.* This will download the repo, with all its contents, onto your computer and automatically set up a local version of the repo. See an example of the command below:

```{R, eval=FALSE}
$ git clone https://github.com/Carlos_Account/test/
```

#####Method 2: Git init

### Modifying Projects

git add
git commit -m
git push, git pull
git remote add origin

### Branching

git checkout

### Merge Conflicts

Carlos and Grace mess up.

Overall:

This cheat sheet is great https://services.github.com/on-demand/downloads/github-git-cheat-sheet.pdf

This setup page is good too
http://kbroman.org/github_tutorial/pages/init.html

## 4. Further reading


## 5. Sources cited

https://git-scm.com/book/en/v2/Getting-Started-Git-Basics
https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup 

