---
title: "Package Development in R"
author: "Asher Spector"
date: "September 30, 2018"
description: "This guide walks through the process of developing R package"
github-repo: "amspector100/packageguidelines"
---

# Introduction

## Table of Contents

This guide is organized into three parts. 

1. First, we'll run through [The proper way to structure and test packages](./package-development.html).
2. Second, we'll discuss [Version Control with Git and Github](./version-control.html)
3. Lastly, we'll [briefly look at a couple of IDEs](./integrated-development-environments.html), which are just pieces of software that make it easier to write packages. 

[Here's a link to a great devtools cheatsheet](https://www.rstudio.com/wp-content/uploads/2015/03/devtools-cheatsheet.pdf) which puts most of the useful commands in this guide in one place.
    
We also wrote a small development example package (called 'devex') which you can find linked [here, on GitHub](https://github.com/amspector100/packageguidelines/tree/master/devex). If you haven't used GitHub yet, don't worry - we'll go over how to use GitHub later. 

Also, this guide is still under development, and we take feedback! If you find anything confusing or think the guide misses important contant, please email amspector100@gmail.com.

## Sources

It's worth acknowledging a couple of people who helped make this guide possible. First of all,  Simo Goshev and Steve Worthington at the IQSS helped design the structure of the guide and edited the content. Second, this guide was written for a different audience, but a lot of its structure and content is based on Hadley Wickham's book [R Packages](http://r-pkgs.had.co.nz/). To help write the sections on testing, we also referenced [Christopher Gandrud's 'Failing Faster' Presentation](
http://slides.com/christophergandrud/failing-faster#/24), and [Christopher Gandrud's Broader Testing Guidelines](https://github.com/IQSS/social_science_software_toolkit/blob/master/testing/recommended_testing_tools_R.md#recommended-testing-tools-and-process-for-r-packages). For the section on on Version Control, we referenced [Karl Broma's Book](http://kbroman.org/GitHub_tutorial/pages/init.html), a [Git-Tower post](https://www.git-tower.com/learn/git/faq/restore-repo-to-previous-revision
), and the GitHub documentation [here](https://git-scm.com/book/en/v2/Getting-Started-Git-Basics) and  [here](https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup) to help write this guide. 






