# Testing

The previous page in the guide discussed [package structure](./package-structure.html). The next page in the guide is the  [Conclusion](./conclusion.html). This page will walk you through the proper way to test packages using the testthat helper package. Another quick reminder: for those who do not want to use RStudio, it's worth following along by reading the [testthat documentation](https://www.rdocumentation.org/packages/testthat/versions/2.0.0) and [source code](https://www.rdocumentation.org/packages/testthat/versions/2.0.0/source). If you've installed and read through the RStudio guide, you're good to go!

You can find the 'devex' example package linked [here, on GitHub](https://github.com/amspector100/packageguidelines/tree/master/devex), if you'd like to look through it while reading the guide. 

## Why should you test?

Suppose Grace has created a package and has been using it for a while, but she decides she'd like to modify one function to improve it. She modifies her function, tests it a bit, and then pushes her package to GitHub. Yet two weeks later, Carlos discovers that the changes she made created a bug in *another* function in the package! This situation is very annoying, especially if Carlos has no idea what has caused the bug or how to fix it. 

The solution to problems like this is to testing your package *systematically* and *automatically*. If Grace had rigorously tested the entire package before pushing it to GitHub, Carlos would never have had to deal with the new bug- Grace would have found out immediately. In other words, a good principle in package devleopment is to make sure your code *fails as fast as possible,* so you can find out and fix it. Of course, all programmers test their code, but not everyone tests systematically and automatically. 

We'll split this page of the guide into two big parts. First, we'll talk creating automatic *unit tests*, which test individual blocks of code (usually individual functions or classes). Second, we'll talk about the process of *continuous integration* (CI), whch is a process designed to help you test your code continuously in collaboration with others without spending huge amounts of time waiting for testing to finish. Ideally, by the end of this guide, you should be aiming to make your packages *developer-proof* - i.e. if you have collaborators, or someone tries to fix your package, you can proactively prevent them from breaking anything important by developing high-quality tests and using a CI workflow.



